name: AutoRe
main: ml.bmlzootown.autore.AutoRe
version: 0.0.7
author: bmlzootown
description: Automatic restarts.
api-version: 1.18

commands:
   autore:
      description: Changes automatic restart interval (for only this restart), reloads settings, or retrieves information
      permission: autore.ar
      permission-message: You don't have permission for this command
      aliases: [ar]

permissions:
  autore.*:
    description: gives all permissions for AutoRe
    default: op
    children:
      autore.ar:
        description: Gives access to basic AutoRe command(s)
      autore.admin:
        description: Gives access to admin commad(s)